### ISSUE TITLE
Missing var statements in buld/ical.js

### ISSUE THREAD

**Issue by GerryFudd** [kewisch/ical.js#159]
I get a reference error when I run the ical.js file in the browser.  I believe the source of this error is that if the ICAL object is not defined initially, then on line 9 you should have:
  var ICAL = ...

**Comment by kewisch** [comment]
Could you mention which version you are using? https://github.com/mozilla-comm/ical.js/blob/master/build/ical.js#L9 shows nothing like that on line 9 and that block should be making sure the variable is defined. For the browser it sets this.ICAL, which should set it on the window, which should make it available thereafter.

**Comment by GerryFudd** [comment]
I discovered that the error resulted from using babeljs.  The issue doesn't arise when my webpack.config file specifies that ical shouldn't be compiled using babeljs.

In the github repository the line that I was referring to is number 11 (I was looking at the line number in my local directory before).  It seems that babel changes the `typeof exports === 'object'` clause to `true` and that was causing the wrong line to be executed.

**Comment by jamesdixon** [comment]
@kewisch I believe this should be re-opened. I'm experiencing the same issue, except on the server side. I'm running the latest (version 1.1.2) on Node 4.2.1 LTS and am _NOT_ using Babel. 

The fix for me was basically the same thing @GerryFudd mentioned -- adding `var ICAL;` to the top of the file as it isn't explicitly defined elsewhere and causes the following error when running Node:

``` javascript
/Users/jamesdixon/Projects/scout/platform/api/node_modules/ical.js/build/ical.js:11
  ICAL = module.exports;
       ^

ReferenceError: ICAL is not defined
    at Object.<anonymous> (/Users/jamesdixon/Projects/scout/platform/api/node_modules/ical.js/build/ical.js:11:8)
```

If you'd like, I'm more than happy to create a PR unless there is a better way to resolve the issue. Thanks!
