### ISSUE TITLE
Get next istance of event (nodeJS)

### ISSUE THREAD

**Issue by ajitam** [kewisch/ical.js#184]
Hi, I have reoccurring event (WEEKLY, WEEKDAYS).
I init the event

```
var event = new ICAL.Event(eventObject);
```

And I can see that is reoccurring with

```
event.isRecurring()
event.getRecurrenceTypes()
```

How do I get next instance of the event? So for example tomorrow (Saturday) I must find event on Monday.

btw: is there some better Documentation? For example I found `isRecurring` from code
http://mozilla-comm.github.io/ical.js/ is blank

**Comment by kewisch** [comment]
To get the next occurrence you need to use the RecurrenceExpansion API:

``` javascript
var iterator = event.iterator(rangeStart);
var next = iterator.next();
```

Looking at the source I suspect the documentation (and/or code) is wrong, it doesn't seem to me you can specify `rangeStart` without failure. If this is the case, then you can just leave out `rangeStart`, and then iterate through to the current range:

``` javascript
var iterator = event.iterator();
for (var next = iterator.next(); next; next = iterator.next()) {
  if (next.compare(rangeStart) < 0) {
    continue;
  }
  // do stuff, then break when you are done.
}

```

http://mozilla-comm.github.io/ical.js/ is broken probably due to CSP and documentup no longer working. Even if, it doesn't show much more than the start page. What I can offer is full API documentation: http://mozilla-comm.github.io/ical.js/api which is also linked from the README.

**Comment by ajitam** [comment]
Great, THX!

Sorry I missed the documentation page.

**Comment by kewisch** [comment]
No problem at all, feel free to create new issues if you have questions in the future.
