### ISSUE TITLE
convert_time does not work

### ISSUE THREAD

**Issue by strokyl** [kewisch/ical.js#213]
Hello,
when I try to use ICAL.Timezone.convert_time, it does not work. Actually I think it's more an issue with ICAL.Timezone.utcOffset.
Is it me which is using ICAL.js wrong or is it a bug.

```
ICAL.Timezone.convert_time(ICAL.Time.fromJSDate(new Date()), new ICAL.Timezone({tzid: 'Europe/Berlin'}), ICAL.Timezone.utcTimezone)
TypeError: Cannot call method 'getAllSubcomponents' of null
    at Object.ICAL.Timezone._ensureCoverage (/home/lduzan/rse/node_modules/ical.js/build/ical.js:4136:39)
    at Object.utcOffset (/home/lduzan/rse/node_modules/ical.js/build/ical.js:4027:12)
    at Function.icaltimezone_convert_time [as convert_time] (/home/lduzan/rse/node_modules/ical.js/build/ical.js:4315:31)
    at repl:1:16
    at REPLServer.self.eval (repl.js:110:21)
    at Interface.<anonymous> (repl.js:239:12)
    at Interface.emit (events.js:95:17)
    at Interface._onLine (readline.js:203:10)
    at Interface._line (readline.js:532:8)
    at Interface._ttyWrite (readline.js:761:14)

```

**Comment by kewisch** [comment]
Hi Luc, nice to hear from you. When generating an `ICAL.Timezone` instance, you must pass more than just the tzid. You need to include the VTIMEZONE component that represents the timezone. The error happens because it is missing and therefore it is trying to get the subcomponents of a null component.

**Comment by strokyl** [comment]
The thinks is I am getting a timezone from a Ical.Event.startDate which has a timezone which is 'Europe/Berlin' but it does not have a zone attribute.
So I do not really know how to create a ICAL.Timezone from this date.
Thank you for your fast reply

**Comment by kewisch** [comment]
You need to hold a list of timezones, this is what ICAL.TimezoneService is meant for. The olson timezone database is at https://www.iana.org/time-zones/repository/tz-link.html. Lightning uses http://dxr.mozilla.org/comm-central/source/calendar/timezones/zones.json as the data source and generates a wrapper around `ICAL.Timezone` here: http://dxr.mozilla.org/comm-central/source/calendar/base/src/calTimezoneService.js#205

Lightning does not directly use the `ICAL.TimezoneService`, but you may choose to do so since you don't have a previous timezone service you need to wrap.
