### ISSUE TITLE
VTIMEZONE / Timezone usage/handling

### ISSUE THREAD

**Issue by castaway** [kewisch/ical.js#455]
https://github.com/mozilla-comm/ical.js/blob/dcfe5a67527e73f54db21fbc31f23670a29704b8/lib/ical/time.js#L1139

^^ I assume this should be "zone: zone"?

**Comment by castaway** [comment]
Hm, no I may be a nitwit - fromData uses it to lookup the correct timezone in the TimeZoneService (if previously registered?)

**Comment by kewisch** [comment]
Yeah one is for the actual zone object, the other is for a timezone string that gets looked up. Agree it is confusing though. Is this causing issues somewhere else?

**Comment by castaway** [comment]
Only in that it silently does nothing useful if I haven't previously manually registered the timezones on the TimezoneService - would you take a patch with a parse(?) option to register them?

**Comment by kewisch** [comment]
The timezone service should normally be pre-filled with the standard iana zones, this is something to be done outside of the library since it should always be the latest version.

Zones provided by vtimezone should somehow be made available during parsing, but I'm not sure they should be added to the timezone service since they are local to the vcalendar being parsed.

If you keep that in mind I'm happy to take a patch!

**Comment by castaway** [comment]
Hmm, so if we don't add the vtimezones to the timezone service, how do we expect start/end times to be correctly timezoned? Currently I have this:

``` typescript
        let component = new ICAL.Component(ICAL.parse(ical));
        if (component.getFirstSubcomponent('vtimezone')) {
            for (const tzComponent of component.getAllSubcomponents('vtimezone')) {
                const tz = new ICAL.Timezone({
                    tzid:      tzComponent.getFirstPropertyValue('tzid'),
                    component: tzComponent,
                });

                if (!ICAL.TimezoneService.has(tz.tzid)) {
                    ICAL.TimezoneService.register(tz.tzid, tz);
                }
            }
        }
        component = ICAL.helpers.updateTimezones(component);
        // Skip exceptions, ICAL.Event will add them as related items.
        // Assuming this is one event, this should return one item
        // with all the related ones attached to it(!)
        const vevents = component.getAllSubcomponents('vevent')
            .filter((c) => !c.hasProperty('recurrence-id'))
            .map((c) => new ICAL.Event(c, {'strictExceptions': true}));
        // Get the instances (one per date):
        // ICAL.RecurExpansion iterator
        const iterator = vevents[0].iterator();
        let next_time;
        let counter = 0;
        while (counter++ <= 200 && ( next_time = iterator.next() )) {
            const details = vevents[0].getOccurrenceDetails(next_time);
            events.push(
                new RunboxCalendarEvent(id, details.item, details.startDate, details.endDate));
        }
        return events;
```

Without the Timezone service registering, the start/end times on the event objects are floating. My thought was a patch that essentially does the manual registering above (if a parse option asks it to), which would sort that issue out. If vtimezone items werent intended to go into the service, where would code go to set those on start/end dates?

I think a minimum change would be, add a flag for stricter checking, so if that "timezone" string I originally mentioned can't be turned into a zone, we get an exception. I'd prefer something to fix the above too though..

**Comment by dilyanpalauzov** [comment]
Use case: a user uploads VEVENT including VTIMEZONE over CalDAV.  The CalDAV server support [RFC 7808 Time Zone Data Distribution Service](https://tools.ietf.org/html/rfc7808) and [RFC 7809 Calendaring Extensions to WebDAV (CalDAV): Time Zones by Reference](https://tools.ietf.org/html/rfc7809).  This essentially means, that whenever a CUA uploads a VEVENT with TZ definitions and the CalDAV/TZDIST server knows the Timezone definitions, the server may strip VTIMEZONEs from the file. 

This is a very good idea, since all operating systems have nearly the same understanding for each timezone, and sending TZ data back and forward has no added value.

Eventually a VEVENT with stripped VTIMEZONE is sent to ical.js .

To fill the Timezone service with timezone data, the data has to be in VTIMEZONE format, that is generated from IANA TZdata using a vzic tool.  The vzic command inserts in each VTIMEZONE/TZID a vendor prefix, that needs to be stripped before the file is sent to the timezone service.

I know two vzic tools:
* https://github.com/libical/vzic which by default inserts a vendor prefix, and
* https://github.com/cyrusimap/cyrus-timezones/tree/master/vzic which by default does not insert a vendor prefix, but can choose slightly different TZID for the same input, while keeping the other TZID as TZID-ALIAS-OF property.

ical.js does not handle the [TZID-ALIAS-OF](https://tools.ietf.org/html/rfc7808#section-7.2) property.

A little bit more on the difference between cyrus-vzic and libical-vzic can be found at https://github.com/cyrusimap/cyrus-imapd/issues/3006 .

How ical.js is supposed to work with vendor prefixes in TZID I do not know, neither do I remember if I ever tried to check if passing an alias to TimezoneService.register(ALIAS, ZONEFILE) does acknowledge on TimezoneService.get() both the alias passed as first parameter to register() and the Timezone-name as TZID in the ZONEFILE.

Please keep these considerations in mind when working on the TimezoneService.

The other thing to take into account when considering whether you want to provide a patch is that pull-requests may or may not get traction within reasonable time.  E.g. ical.js does wrap/fold ala-JavaScript bytewise long lines.  When the folding is performed in the middle of UTF-16 sequence (say between the high and low “surrogate”), the string is not valid UTF anymore and unfolding it does not return the original string.  [A patch on this](https://github.com/mozilla-comm/ical.js/pull/439) is, for reasons that are irrelevant, as a matter of fact, not tackled withing half a year.

**Comment by castaway** [comment]
I have no intentions of changing the TimezoneService, only the parsing, with a) a flag for the user to say "register any timezones you find", and b) the registering, if said flag is true.

Is there documentation somewhere I am missing, that suggests the adding of timezone data using a vzic tool ? (If not would you take a patch for doc improvements too?)

**Comment by castaway** [comment]
@dilyanpalauzov as far as I can see, our caldav server doesn't remove the vtimezones, btw - its Sabre. We currently handle vtimezones on the frontend.

I can however see that it would make more sense to use a/the central repository of them.

**Comment by kewisch** [comment]
There is now an ICAL.timezones.js that can be built if you download the sources. I'm not automating that currently because I'd need to keep the timezones up to date when IANA releases, there is an issue open to consider options on how to do so. Closing this issue for now, if anything else pops up please open a new one!
