### ISSUE TITLE
PROJECT IS DEAD?

### ISSUE THREAD

**Issue by TimDaub** [kewisch/ical.js#463]
Hi,

a year ago I sent a PR to this repo. Since then nothing of substance has happened. I want to rely on this code, but I keep wondering if the project is still alive. @mozilla-comm can someone please just give a statement of what is happening? Then we can just fork or move on. Thanks.

Edit: I'm using your project in [simple-caldav](https://github.com/TimDaub/simple-caldav/), hence I wanna know.

**Comment by kewisch** [comment]
Hi Tim, sorry the experience hasn't been great. It is true I haven't been able to catch up on ical.js, though I really like the library and think it has a lot of potential for the future. I do catch up in bursts once in a while, though my main concern is around the library's use in Thunderbird.

Especially for some pull requests I'm concerned how they would affect use in Thunderbird. Now surely I could say tests will cover it and when Thunderbird pulls from upstream they can fix their issues, but I know how painful this was upgrading libical in Thunderbird.

I've started a conversation with @mkmelin to see what we can do about this, I see a few options:
* Have someone else from the Thunderbird team co-maintain the library, who can make sure pull requests will continue to work well. We have someone who may be able to take that on, though they need to finish up some other work first.
* Just go ahead and commit here as long as ical.js tests pass, but have a regular schedule for Thunderbird where the library is pulled from upstream.
* Add [some sort of automation](https://github.com/kewisch/action-thunderbird-tests) to this repo that would run the Thunderbird tests with the updated ical.js to make sure those tests are still passing
* Add some sort of automation to Thunderbird that would pull the latest ical.js from main branch when building nightlys and run the respective tests.

**Comment by dilyanpalauzov** [comment]
ical.js does work independently of Thunderbird and could be applied in scenarios, which Thunderbird does not offer.  If somebody is willing to maintain the library, that person shall not be excluded, just because the person is not part of Thunderbird.

If you are looking for somebody else to co-maintain the ical.js library, please state publicly so.

**Comment by notKamui** [comment]
Another thing is, some libraries already depend on ical.js (see @fullcalendar), and the version on npm is already way too old for it's own good even though the code on the master branch is (supposed to be) stable.

The current version (1.4.0) has a bug that occurs with strict mode where the ICAL variable is never declared ; this bug has been fixed since then, but never pushed to npm. So we also end up with a bugged fullcalendar.

**Comment by kewisch** [comment]
Working something out, see #646. I'm not saying the co-maintainer needs to be someone in Thunderbird, though I struggle handing out co-maintainership so I'm going to need some level of vetting and trust (recent events around xz show why, though this library is certainly not as critical).
