### ISSUE TITLE
Any breaking changes when going from v1.5 to v2.0?

### ISSUE THREAD

**Issue by jungalwala** [kewisch/ical.js#650]
Are there any breaking changes when migrating from v1.5 to 2.0?

Jay

**Comment by kewisch** [comment]
Based on my recollection of the ES6 changes, a quick skim through the diff, and an educated guess based on the changelog, I don't think there are any breaking changes. There may be some differences on how the library is imported given the ES6 changes and how node works, but this should be trivial.

I mainly did the bump to 2.0 out of an abundance of caution given the ES6 changes.

**Comment by kewisch** [comment]
Ah yes, there are some breaking changes w.r.t. imports and browsers. You can't simply <script src> import it there, you'll need
```html
<script type="module">
import ICAL from "https://unpkg.com/ical.js";

// ...
</script>
```

The es5 version will need some massaging so that it would work in a browser, right now it just sets `module.exports`, I need to file an issue to update the README and es5 version for browser use.

**Comment by kewisch** [comment]
Closing this in favor of the other issue
